name: Common

permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: mise run --force check
