name: Python - E2E Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'python/**'

defaults:
  run:
    working-directory: python

jobs:
  test:
    timeout-minutes: 120
    name: Tests
    runs-on: ubuntu-latest
    env:
      TEST_NUM_WORKERS: ${{ vars.TEST_NUM_WORKERS }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Poetry
        run: pipx install poetry==2.1.1
      - name: Install Poe
        run: pipx install poethepoet
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --all-extras
      - name: Build
        run: poetry build
      - name: Run E2E Tests
        run: poe test --type e2e -- --ignore tests/examples/test_examples.py
        env:
          OLLAMA_API_BASE: ${{ secrets.OLLAMA_API_BASE }}
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
          BEEAI_OPEN_METEO_TOOL_PROXY: ${{ secrets.PROXY }}
          BEEAI_DDG_TOOL_PROXY: ${{ secrets.PROXY }}
      - name: Run Examples
        run: poe test --type e2e -- tests/examples/test_examples.py
        env:
          OLLAMA_API_BASE: ${{ secrets.OLLAMA_API_BASE }}
          OLLAMA_API_KEY: ${{ secrets.OLLAMA_API_KEY }}
          BEEAI_OPEN_METEO_TOOL_PROXY: ${{ secrets.PROXY }}
          BEEAI_DDG_TOOL_PROXY: ${{ secrets.PROXY }}
